[project]
name = "primevox"
version = "0.1.0"
description = "primevox is a Python SDK for analyzing prime number properties, twin primes, prime gaps, factoring composite numbers, and implementing efficient number-theoretic algorithms."
authors = [
    {name = "Mike Lawrenchuk", email = "25318794+MikeLawrenchuk@users.noreply.github.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["sympy (>=1.13.3,<2.0.0)", "networkx (>=3.4.2,<4.0.0)", "matplotlib (>=3.10.1,<4.0.0)", "scipy (>=1.15.2,<2.0.0)"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

