name: CI - PrimeVox SDK Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.1.2  # explicitly stable Poetry version
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install Dependencies
      run: |
        poetry install --no-interaction --no-root --only main,dev

    - name: Lint with Ruff
      run: |
        poetry run ruff check .

    - name: Run Tests with Pytest
      run: |
        poetry run pytest

